### ISSUE TITLE
Unsorted list in a danger-block has a dark font-color instead of tech color white when using the standard-template

### ISSUE THREAD

**Issue by cziehr** [selfthinker/dokuwiki_plugin_wrap#126]
I'm using the wrap-plugin in combination with the dokuwiki-template (standard).

When I put some unsorted list items in a danger-block, then the font color is dark one (#333) instead of white. It seems that this is caused by the dokuwiki template.

Have a look at http://wiki.einsatzleiterwiki.de/doku.php?id=gefaehrliche_stoffe_gueter:chemisch:klasse_2:stoffe:kohlenmonoxid and scroll down a bit for an example of this behaviour.

**Comment by selfthinker** [comment]
This will also be true for anything else which has a defined colour (e.g. links) and will be difficult to override and keep flexible at the same time (especially as the safety colours are following a standard and cannot be adjusted, e.g. to be lighter, and because their colours vary so much in contrast). I was aware of it when the safety notes were created but didn't know how to reliably fix it and hoped people would only put text inside them.

Instead of trying to fix the colour of the list items (and other elements), I wonder if it makes more sense to change the safety boxes to just have coloured borders instead of having their whole background coloured?
Like this:
![image](https://cloud.githubusercontent.com/assets/108893/14232755/6337d71e-f9ac-11e5-8fe0-72420d47b0cc.png)

**Comment by selfthinker** [comment]
Actually, changing the safety boxes to have coloured borders would be against the standard (ISO 3864 or ANSI Z535), so that is not an option.

I have now fixed this in #169, but am not 100% sure if that doesn't create any unwanted side effects.
