### ISSUE TITLE
class for "onlymobile"?

### ISSUE THREAD

**Issue by rwoldu** [selfthinker/dokuwiki_plugin_wrap#129]
Hi,

is it possible to develop a class that allows to show text (or maybe replaces text) only when accessing via mobile devices?
E.g. as the syntax for wrap onlyprint and wrap noprint?

Thanks in advance! 

(sorry if it the wrong place for requests, but I am not sure where to ask...)

**Comment by selfthinker** [comment]
The reason why `onlyprint` and `noprint` is possible is because if something is printed can be determined purely by CSS. If something is viewed on a mobile phone cannot reliably be determined via CSS only. The question is also: How do you define "mobile"?
You can potentially add a class that checks for viewport (or screen) width, but that has not really anything to do with being a mobile phone. Doing that would also be impossible to implement consistently across all the different templates as every template uses different width values.

As such I would not want to support it, because it's not really possible. (Unless there will be a CSS feature in the future which can be used for this kind of thing.)
