### ISSUE TITLE
parser bug when using WRAP inside link

### ISSUE THREAD

**Issue by soft2u** [selfthinker/dokuwiki_plugin_wrap#149]
Using wrap inside link are not working well.
Using this
`[[link:to:page|<wrap em>Link to page</wrap>]]`

I expect to get 

`<a href="/wiki/doku.php?id=link:to:page" class="wikilink1" title="link:to:page" rel="nofollow"><span class="wrap_em">Link to page</span></a>`

but I get 
`<a href="/wiki/doku.php?id=link:to:page" class="wikilink1" title="link:to:page" rel="nofollow">&lt;wrap em&gt;Link to page&lt;/wrap&gt;</a>`

Thank you

**Comment by selfthinker** [comment]
That is an intentional limitation of DokuWiki (not the Wrap plugin) and is not fixable. See https://www.dokuwiki.org/faq:headerlinks for a further explanation.

You could overcome that by putting the wrap outside of the link, e.g. `<wrap em>[[link:to:page|Link to page]]</wrap>`, although that might not give the exact same result you were expecting.
