### ISSUE TITLE
Multi-column (e.g. col3) not working in firefox

### ISSUE THREAD

**Issue by ggieling** [selfthinker/dokuwiki_plugin_wrap#158]
I am testing a dokuwiki environment and in a page that in essence just lists a vast amount of links I use the tabbox plugin (https://www.dokuwiki.org/plugin:tabbox) to present the information in a more condensed manner.
Since some of the listings are still quite long I decided to use the Multicolumn functionality of the wrap plugin (https://www.dokuwiki.org/plugin:wrap) as included in the standard installation.  This brings the expected result in the Chromium and google Chrome browsers, but does not work as expected in firefox (both linux: 58.0.2 (64-bit) as windows: 58.0.2 (32-bit)).
I use as default template the bootstrap3 template (but not the bootswrapper plugin), but since it does work as expected in chromium and google chrome, I do not expect this to be related to the template or other plugins.

The page in the testsite can be found here (http://won2/content/public/en/patinf#tab__bibliographic1)

**Comment by selfthinker** [comment]
It works fine for me in the default as well as the bootstrap3 template (see screenshot below).
The URL to the test site you gave above is not working. Could you provide an example I can look at?

![](https://user-images.githubusercontent.com/108893/37567203-5c116ae4-2abb-11e8-87da-8fd174f6cee4.png)

**Comment by ggieling** [comment]
Sorry Anika,

I had just moved this site from the test environment to what will become the production environment.

The link in the production environment is <http://www.won-nl.org/content/open/nl/patinf#tab__bibliographic1>

Gerben Gieling
IP Specialist

Synthon BV
Microweg 22 | P.O. Box 7071 | 6503 GN  Nijmegen | The Netherlands
T: +31(0)24 37 27 700 | F: +31(0)24 37 27 705 | www.synthon.com<http://www.synthon.com>

**Comment by selfthinker** [comment]
Thanks for the link.
This is definitely a bug in Firefox, to do with the bootstrap3 template setting `overflow: hidden` on the list. I have reported the bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1446826

I am not sure why bootstrap3 has that `overflow: hidden` there, so the following could break something else in the template, but you could fix this specific issue by overwriting it in your [user styles](https://www.dokuwiki.org/devel:css#user_styles) like so:

```
.fix-media-list-overlap {
  overflow: visible;
}
```

**Comment by selfthinker** [comment]
Ah, I think I know what `.fix-media-list-overlap` is. I think it's trying to fix what happens when you have a list next to a (left) floating image. We tried to fix it in the default template but whatever we tried caused more problems, see https://bugs.dokuwiki.org/1950.html for the history behind that.
